//! Client-side knock-PSK loader.
//!
//! Symmetric to the server's `knock_keygen::load`. The client
//! never MINTS a knock PSK (that's a server-operator concern —
//! the server generates it once and distributes the SAME bytes
//! to every authorized client). The client only ever LOADS the
//! file it was given.
//!
//! ## File format
//!
//! Byte-for-byte identical to what `proteus-server knock-keygen`
//! produces:
//!
//! ```text
//!   # Generated by proteus-server knock-keygen — server-side knock PSK
//!   # 32 bytes (256 bits) of OsRng. KEEP SECRET. chmod 0600.
//!   uIHvhG0A7HqSTsyVdjm9gcbJ9TiR7n90fXQvqUP106Q=
//! ```
//!
//! Hand-editable; loader skips `#`-comment lines and rejects
//! multi-data-line files (so a half-edit during emergency
//! rotation surfaces clearly).
//!
//! ## Why a separate module from the server's `knock_keygen`
//!
//! The two crates (`proteus-server` and `proteus-client`) don't
//! share a workspace lib — the client doesn't depend on the
//! server crate. Lifting the loader into `proteus-handshake`
//! would also work, but the loader's only consumer is the YAML
//! config layer and it's three pages of code; duplicating it
//! keeps the dep DAG flat. The crucial invariant — the
//! file-format ↔ protocol-consumer contract — is pinned by the
//! `loaded_key_round_trips_through_knock_compute_verify` test
//! in BOTH crates.

use std::fs;
use std::path::Path;

use base64::Engine;
use proteus_handshake::knock::KNOCK_PSK_LEN;
use zeroize::Zeroizing;

/// Loader-side errors. Distinct from anything else in the
/// codebase so the YAML-load path can surface
/// "knock_psk_file invalid" with an actionable message.
#[derive(thiserror::Error, Debug)]
pub enum KnockPskLoadError {
    /// File could not be opened / read.
    #[error("io {0:?}: {1}")]
    Io(std::path::PathBuf, std::io::Error),
    /// File contained no non-comment lines.
    #[error("{0:?}: empty (no non-comment data line)")]
    Empty(std::path::PathBuf),
    /// File contained more than one non-comment data line.
    /// Operators editing the file by hand may have appended a
    /// second key; reject so the loader doesn't silently use
    /// the first or last.
    #[error("{0:?}: multiple non-comment data lines — should be exactly one b64 line")]
    MultipleDataLines(std::path::PathBuf),
    /// Base64 decode failed.
    #[error("{0:?}: base64 decode failed: {1}")]
    Base64(std::path::PathBuf, String),
    /// Decoded byte length didn't match the protocol-required 32.
    #[error("{path:?}: decoded {got} bytes, expected {want}")]
    WrongLength {
        /// The path that failed.
        path: std::path::PathBuf,
        /// What we got.
        got: usize,
        /// What the protocol requires.
        want: usize,
    },
}

/// Parse a knock-PSK file in the format the server's
/// `knock-keygen` writes. Returns the 32 raw bytes ready to
/// hand to [`proteus_handshake::knock::KnockPsk::from_bytes`].
///
/// Iter-169: secret-bearing intermediates scrubbed on drop —
/// symmetric to the server-side `knock_keygen::load` fix in the
/// same iteration. `body` (full file contents incl. the b64 PSK)
/// and `raw` (decoded PSK bytes) are both substitutable for the
/// PSK; pre-iter-169 they lingered on the heap until later
/// activity reused their backings.
pub fn load(path: &Path) -> Result<Zeroizing<[u8; KNOCK_PSK_LEN]>, KnockPskLoadError> {
    let body = Zeroizing::new(
        fs::read_to_string(path).map_err(|e| KnockPskLoadError::Io(path.to_path_buf(), e))?,
    );
    let mut data_line: Option<&str> = None;
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if data_line.is_some() {
            return Err(KnockPskLoadError::MultipleDataLines(path.to_path_buf()));
        }
        data_line = Some(trimmed);
    }
    let line = data_line.ok_or_else(|| KnockPskLoadError::Empty(path.to_path_buf()))?;
    let raw = Zeroizing::new(
        base64::engine::general_purpose::STANDARD
            .decode(line)
            .map_err(|e| KnockPskLoadError::Base64(path.to_path_buf(), e.to_string()))?,
    );
    if raw.len() != KNOCK_PSK_LEN {
        return Err(KnockPskLoadError::WrongLength {
            path: path.to_path_buf(),
            got: raw.len(),
            want: KNOCK_PSK_LEN,
        });
    }
    // Iter-191: return Zeroizing<[u8; 32]> so the caller's
    // stack copy scrubs on drop too. Same fix as the matching
    // proteus-server::knock_keygen::load in this iteration.
    let mut out = Zeroizing::new([0u8; KNOCK_PSK_LEN]);
    out.copy_from_slice(&raw);
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use base64::Engine;
    use proteus_handshake::knock::{compute_knock, verify_knock, KnockPsk};

    fn tmp_path(suffix: &str) -> std::path::PathBuf {
        let base = std::env::var("CARGO_TARGET_TMPDIR").unwrap_or_else(|_| "/tmp".to_string());
        let p = std::path::PathBuf::from(format!(
            "{base}/proteus-client-knock-psk-{suffix}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        let _ = std::fs::remove_file(&p);
        p
    }

    fn write_psk(path: &std::path::Path, bytes: &[u8]) {
        let b64 = base64::engine::general_purpose::STANDARD.encode(bytes);
        std::fs::write(
            path,
            format!(
                "# Generated by proteus-server knock-keygen — server-side knock PSK\n\
                 # 32 bytes (256 bits) of OsRng. KEEP SECRET. chmod 0600.\n\
                 {b64}\n"
            ),
        )
        .unwrap();
    }

    #[test]
    fn load_recovers_exact_bytes_from_server_format() {
        let p = tmp_path("recover");
        let key = [0xA1; KNOCK_PSK_LEN];
        write_psk(&p, &key);
        let loaded = load(&p).unwrap();
        assert_eq!(*loaded, key);
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn loaded_key_round_trips_through_knock_compute_verify() {
        // The CRITICAL test: pins that the file format the
        // client loads is byte-for-byte compatible with what
        // the server's knock primitive consumes. Drift here =
        // probe-resistance gate silently fails open.
        let p = tmp_path("compute-verify");
        let key = [0x33; KNOCK_PSK_LEN];
        write_psk(&p, &key);
        let loaded = load(&p).unwrap();
        let psk = KnockPsk::from_bytes(*loaded);
        let client_random = [0xCC; 32];
        let now = 1_715_900_000u64;
        let tok = compute_knock(&psk, &client_random, now);
        verify_knock(&psk, &client_random, &tok, now).expect("round-trip must verify");
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_empty_file() {
        let p = tmp_path("empty");
        std::fs::write(&p, "# comment only\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, KnockPskLoadError::Empty(_)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_multiple_data_lines() {
        let p = tmp_path("multi");
        std::fs::write(&p, "# header\nFIRSTKEY==\nSECONDKEY==\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, KnockPskLoadError::MultipleDataLines(_)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_bad_base64() {
        let p = tmp_path("bad-b64");
        std::fs::write(&p, "# header\n!!! not base64 !!!\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, KnockPskLoadError::Base64(_, _)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_wrong_length() {
        let p = tmp_path("short");
        let short = base64::engine::general_purpose::STANDARD.encode([0xAB; 16]);
        std::fs::write(&p, format!("# short key\n{short}\n")).unwrap();
        let e = load(&p).unwrap_err();
        assert!(
            matches!(
                e,
                KnockPskLoadError::WrongLength { got, want, .. }
                    if got == 16 && want == KNOCK_PSK_LEN
            ),
            "expected WrongLength{{got=16,want=32}}, got {e:?}"
        );
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_handles_missing_file() {
        let p = tmp_path("missing");
        let _ = std::fs::remove_file(&p);
        let e = load(&p).unwrap_err();
        assert!(matches!(e, KnockPskLoadError::Io(_, _)));
    }

    #[test]
    fn load_accepts_extra_blank_lines() {
        // Operators editing the file may leave a trailing blank.
        // We already strip via `.trim()` + skip-empty, but pin
        // it as a test so a future loader regression catches.
        let p = tmp_path("trailing-blank");
        let key = [0x77; KNOCK_PSK_LEN];
        let b64 = base64::engine::general_purpose::STANDARD.encode(key);
        std::fs::write(&p, format!("# c1\n\n# c2\n\n{b64}\n\n\n")).unwrap();
        let loaded = load(&p).unwrap();
        assert_eq!(*loaded, key);
        let _ = std::fs::remove_file(&p);
    }
}
