//! `proteus-server admin status` — SSH-friendly snapshot.
//!
//! Operators triaging a live server want one quick look at:
//! - Process up/ready state.
//! - In-flight sessions + lifetime totals.
//! - Defense layer rejection counters (so they can spot a fresh DoS).
//! - Sessions reaped by idle / byte budget.
//!
//! `curl /metrics | grep` works but means remembering the metric
//! names and the bearer token. This subcommand wraps that with
//! semantic grouping + a one-pass parser.
//!
//! Reads `--url` (default `http://127.0.0.1:9090/metrics`). Auth via
//! `--token-file` (or `PROTEUS_METRICS_TOKEN` env var). No external
//! Prometheus client lib: the exposition format is line-based plain
//! text, easy to parse by hand.

use std::collections::BTreeMap;
use std::fmt;
use std::io::{Read, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::Path;
use std::time::Duration;

/// All counters / gauges we recognize. Unknown counter names from the
/// exposition are ignored (forward-compatible — newer servers can add
/// counters without breaking older admin clients).
#[derive(Debug, Default, Clone)]
pub struct MetricsSnapshot {
    pub up: u64,
    pub ready: u64,
    pub in_flight_sessions: u64,
    pub sessions_accepted: u64,
    pub handshakes_succeeded: u64,
    pub handshakes_failed: u64,
    pub handshake_timeouts: u64,
    pub handshake_budget_rejected: u64,
    pub rate_limited: u64,
    pub conn_limit_rejected: u64,
    pub firewall_denied: u64,
    pub user_rate_rejected: u64,
    pub cover_forwards: u64,
    pub tx_bytes: u64,
    pub rx_bytes: u64,
    pub aead_drops: u64,
    pub ratchets: u64,
    pub session_idle_reaped: u64,
    pub session_byte_budget_exhausted: u64,
    /// Counters we recognized by name but don't have a dedicated
    /// field for yet. Operators see them under "Other".
    pub other: BTreeMap<String, u64>,
}

impl MetricsSnapshot {
    /// Parse a Prometheus 0.0.4 exposition body.
    ///
    /// Tolerant: silently ignores `#` comment lines, blank lines,
    /// label-bearing series (none of our counters have labels), and
    /// malformed value lines. We deliberately use the simplest
    /// possible parser — the body is generated by our own
    /// hand-rolled emitter, so format guarantees are tight.
    #[must_use]
    pub fn parse(body: &str) -> Self {
        let mut s = Self::default();
        for line in body.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            // Each value line is `name value`; reject anything with
            // labels (a `{` between name and value), per above.
            let (name, value) = match line.split_once(' ') {
                Some((n, v)) => (n.trim(), v.trim()),
                None => continue,
            };
            if name.contains('{') {
                continue;
            }
            let v: u64 = match value.parse() {
                Ok(v) => v,
                Err(_) => continue,
            };
            match name {
                "proteus_up" => s.up = v,
                "proteus_ready" => s.ready = v,
                "proteus_in_flight_sessions" => s.in_flight_sessions = v,
                "proteus_sessions_accepted_total" => s.sessions_accepted = v,
                "proteus_handshakes_succeeded_total" => s.handshakes_succeeded = v,
                "proteus_handshakes_failed_total" => s.handshakes_failed = v,
                "proteus_handshake_timeouts_total" => s.handshake_timeouts = v,
                "proteus_handshake_budget_rejected_total" => s.handshake_budget_rejected = v,
                "proteus_rate_limited_total" => s.rate_limited = v,
                "proteus_conn_limit_rejected_total" => s.conn_limit_rejected = v,
                "proteus_firewall_denied_total" => s.firewall_denied = v,
                "proteus_user_rate_rejected_total" => s.user_rate_rejected = v,
                "proteus_cover_forwards_total" => s.cover_forwards = v,
                "proteus_tx_bytes_total" => s.tx_bytes = v,
                "proteus_rx_bytes_total" => s.rx_bytes = v,
                "proteus_aead_drops_total" => s.aead_drops = v,
                "proteus_ratchets_total" => s.ratchets = v,
                "proteus_session_idle_reaped_total" => s.session_idle_reaped = v,
                "proteus_session_byte_budget_exhausted_total" => {
                    s.session_byte_budget_exhausted = v;
                }
                // Unknown counter — keep it under "Other" so a future
                // metric still surfaces to the operator without an
                // admin-CLI rebuild.
                _ if name.starts_with("proteus_") => {
                    s.other.insert(name.to_string(), v);
                }
                _ => {}
            }
        }
        s
    }

    /// Sum of all rejection counters (DoS-defense pipeline).
    #[must_use]
    pub fn total_rejected(&self) -> u64 {
        self.firewall_denied
            .saturating_add(self.handshake_budget_rejected)
            .saturating_add(self.rate_limited)
            .saturating_add(self.conn_limit_rejected)
            .saturating_add(self.user_rate_rejected)
    }
}

impl fmt::Display for MetricsSnapshot {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let live_marker = if self.up == 1 { "LIVE" } else { "DOWN" };
        let ready_marker = if self.ready == 1 { "READY" } else { "DRAINING" };
        writeln!(
            f,
            "============================================================"
        )?;
        writeln!(f, " proteus-server status — {live_marker} / {ready_marker}",)?;
        writeln!(
            f,
            "============================================================"
        )?;

        macro_rules! row {
            ($label:expr, $value:expr) => {
                writeln!(f, "  {:<32} {}", $label, $value)
            };
        }

        writeln!(f, " Sessions")?;
        row!("in_flight_sessions", self.in_flight_sessions)?;
        row!("sessions_accepted_total", self.sessions_accepted)?;
        row!("handshakes_succeeded_total", self.handshakes_succeeded)?;
        row!("handshakes_failed_total", self.handshakes_failed)?;
        row!("handshake_timeouts_total", self.handshake_timeouts)?;
        writeln!(f)?;

        writeln!(f, " Defense pipeline (rejections)")?;
        row!("firewall_denied", self.firewall_denied)?;
        row!("handshake_budget_rejected", self.handshake_budget_rejected)?;
        row!("rate_limited", self.rate_limited)?;
        row!("conn_limit_rejected", self.conn_limit_rejected)?;
        row!("user_rate_rejected", self.user_rate_rejected)?;
        row!("cover_forwards", self.cover_forwards)?;
        row!("total_rejected", self.total_rejected())?;
        writeln!(f)?;

        writeln!(f, " Session teardown causes")?;
        row!("session_idle_reaped", self.session_idle_reaped)?;
        row!(
            "session_byte_budget_exhausted",
            self.session_byte_budget_exhausted
        )?;
        writeln!(f)?;

        writeln!(f, " Throughput")?;
        row!(
            "tx_bytes_total",
            format!("{} ({})", self.tx_bytes, human_bytes(self.tx_bytes))
        )?;
        row!(
            "rx_bytes_total",
            format!("{} ({})", self.rx_bytes, human_bytes(self.rx_bytes))
        )?;
        row!("ratchets_total", self.ratchets)?;
        row!("aead_drops_total", self.aead_drops)?;

        if !self.other.is_empty() {
            writeln!(f)?;
            writeln!(f, " Other (unrecognized counters)")?;
            for (k, v) in &self.other {
                row!(k.as_str(), v)?;
            }
        }
        writeln!(
            f,
            "============================================================"
        )?;
        Ok(())
    }
}

/// Render `n` as `"X.YZ unit"` (KiB/MiB/GiB/TiB). Duplicated from
/// the startup module to keep this file dep-free; admin CLI ships
/// as a separate code path.
fn human_bytes(n: u64) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * KIB;
    const GIB: u64 = 1024 * MIB;
    const TIB: u64 = 1024 * GIB;
    if n >= TIB {
        format!("{:.2} TiB", n as f64 / TIB as f64)
    } else if n >= GIB {
        format!("{:.2} GiB", n as f64 / GIB as f64)
    } else if n >= MIB {
        format!("{:.2} MiB", n as f64 / MIB as f64)
    } else if n >= KIB {
        format!("{:.2} KiB", n as f64 / KIB as f64)
    } else {
        format!("{n} B")
    }
}

/// Errors surfaced by the `status` HTTP client.
#[derive(Debug, thiserror::Error)]
pub enum AdminError {
    #[error("URL must look like http://host:port/path, got {0:?}")]
    BadUrl(String),
    #[error("resolve {0:?}: {1}")]
    Resolve(String, std::io::Error),
    #[error("token file {0:?}: {1}")]
    Token(String, std::io::Error),
    #[error("connect {0}: {1}")]
    Connect(SocketAddr, std::io::Error),
    #[error("write: {0}")]
    Write(std::io::Error),
    #[error("read: {0}")]
    Read(std::io::Error),
    #[error("HTTP status {0}: {1}")]
    Status(u16, String),
    #[error("response missing body")]
    NoBody,
}

/// Read a bearer token from `path`. Strips trailing newline +
/// whitespace; rejects empty.
pub fn read_token_file(path: &Path) -> Result<String, AdminError> {
    let raw = std::fs::read_to_string(path)
        .map_err(|e| AdminError::Token(path.display().to_string(), e))?;
    let token = raw.trim().to_string();
    if token.is_empty() {
        return Err(AdminError::Token(
            path.display().to_string(),
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "token file is empty after trimming whitespace",
            ),
        ));
    }
    Ok(token)
}

/// Parse a `http://host:port/path` URL into `(host, port, path)`.
/// Deliberately minimal — we accept only `http://` (the metrics
/// endpoint is always plain HTTP; rely on bind-loopback or VPN for
/// confidentiality and bearer for auth, not TLS).
pub fn parse_http_url(url: &str) -> Result<(String, u16, String), AdminError> {
    let rest = url
        .strip_prefix("http://")
        .ok_or_else(|| AdminError::BadUrl(url.to_string()))?;
    let (authority, path) = match rest.find('/') {
        Some(idx) => (&rest[..idx], &rest[idx..]),
        None => (rest, "/"),
    };
    let (host, port) = match authority.rsplit_once(':') {
        Some((h, p)) => {
            let port: u16 = p.parse().map_err(|_| AdminError::BadUrl(url.to_string()))?;
            (h.to_string(), port)
        }
        None => return Err(AdminError::BadUrl(url.to_string())),
    };
    if host.is_empty() {
        return Err(AdminError::BadUrl(url.to_string()));
    }
    Ok((host, port, path.to_string()))
}

/// Synchronous HTTP GET against a `/metrics`-style endpoint. Returns
/// the response body on 200, an [`AdminError::Status`] on anything
/// else. Hand-rolled: no `reqwest` / `ureq` dep needed for one
/// request from inside a CLI.
pub fn http_get(url: &str, token: Option<&str>, timeout: Duration) -> Result<String, AdminError> {
    let (host, port, path) = parse_http_url(url)?;
    let addrs = (host.as_str(), port)
        .to_socket_addrs()
        .map_err(|e| AdminError::Resolve(host.clone(), e))?
        .collect::<Vec<_>>();
    let addr = addrs.into_iter().next().ok_or_else(|| {
        AdminError::Resolve(
            host.clone(),
            std::io::Error::new(std::io::ErrorKind::AddrNotAvailable, "no addrs"),
        )
    })?;

    let mut sock =
        TcpStream::connect_timeout(&addr, timeout).map_err(|e| AdminError::Connect(addr, e))?;
    sock.set_read_timeout(Some(timeout)).ok();
    sock.set_write_timeout(Some(timeout)).ok();

    let mut req = format!(
        "GET {path} HTTP/1.1\r\nHost: {host}:{port}\r\nUser-Agent: proteus-admin\r\nConnection: close\r\n",
    );
    if let Some(t) = token {
        use std::fmt::Write as _;
        let _ = write!(&mut req, "Authorization: Bearer {t}\r\n");
    }
    req.push_str("\r\n");
    sock.write_all(req.as_bytes()).map_err(AdminError::Write)?;

    let mut raw = Vec::with_capacity(8192);
    sock.read_to_end(&mut raw).map_err(AdminError::Read)?;
    let text = String::from_utf8_lossy(&raw).into_owned();

    // Split headers / body on the first \r\n\r\n.
    let split = text.find("\r\n\r\n").ok_or(AdminError::NoBody)?;
    let head = &text[..split];
    let body = &text[split + 4..];

    let mut head_lines = head.lines();
    let status_line = head_lines.next().unwrap_or("");
    let status: u16 = status_line
        .split(' ')
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    if status != 200 {
        return Err(AdminError::Status(status, body.to_string()));
    }
    Ok(body.to_string())
}

/// Top-level driver for the `admin status` subcommand. Fetches
/// `/metrics`, parses, prints. Returns `Ok(())` on success — the
/// caller decides exit code.
pub fn run(
    url: &str,
    token: Option<&str>,
    timeout: Duration,
) -> Result<(), Box<dyn std::error::Error>> {
    let body = http_get(url, token, timeout)?;
    let snap = MetricsSnapshot::parse(&body);
    let _ = std::io::stdout().write_all(snap.to_string().as_bytes());
    Ok(())
}

/// Counter-delta between two snapshots. Positive numbers only:
/// counters can only go up over time (the gauges `in_flight`, `up`,
/// `ready` are absolute values, not deltas — we surface them as
/// `now: N` instead).
///
/// "After minus before" semantics. A negative would mean the counter
/// reset between scrapes (process restart); we saturate-clamp to 0
/// and surface a banner warning.
#[derive(Debug, Default, Clone)]
pub struct MetricsDelta {
    /// Wall-clock seconds between the two scrapes. Used to render
    /// per-second rates ("3 rejected/s").
    pub interval_secs: f64,
    pub sessions_accepted: u64,
    pub handshakes_succeeded: u64,
    pub handshakes_failed: u64,
    pub handshake_timeouts: u64,
    pub handshake_budget_rejected: u64,
    pub rate_limited: u64,
    pub conn_limit_rejected: u64,
    pub firewall_denied: u64,
    pub user_rate_rejected: u64,
    pub cover_forwards: u64,
    pub tx_bytes: u64,
    pub rx_bytes: u64,
    pub aead_drops: u64,
    pub ratchets: u64,
    pub session_idle_reaped: u64,
    pub session_byte_budget_exhausted: u64,
    /// Snapshot at the END of the interval (for gauges).
    pub now_in_flight: u64,
    pub now_up: u64,
    pub now_ready: u64,
    /// True if any counter went DOWN between scrapes — almost
    /// certainly a process restart. Operators want to know.
    pub counter_reset: bool,
}

impl MetricsDelta {
    /// Compute `(b - a)` clamped to non-negative. If `b` is older
    /// than `a` by clock skew the `interval_secs` may be ≤ 0; the
    /// caller can decide whether to render rates.
    #[must_use]
    pub fn between(a: &MetricsSnapshot, b: &MetricsSnapshot, interval_secs: f64) -> Self {
        let mut counter_reset = false;
        // `delta_counter` clamps b<a to 0 and records the reset.
        let delta = |before: u64, after: u64, reset: &mut bool| -> u64 {
            if after < before {
                *reset = true;
                0
            } else {
                after - before
            }
        };
        Self {
            interval_secs,
            sessions_accepted: delta(a.sessions_accepted, b.sessions_accepted, &mut counter_reset),
            handshakes_succeeded: delta(
                a.handshakes_succeeded,
                b.handshakes_succeeded,
                &mut counter_reset,
            ),
            handshakes_failed: delta(a.handshakes_failed, b.handshakes_failed, &mut counter_reset),
            handshake_timeouts: delta(
                a.handshake_timeouts,
                b.handshake_timeouts,
                &mut counter_reset,
            ),
            handshake_budget_rejected: delta(
                a.handshake_budget_rejected,
                b.handshake_budget_rejected,
                &mut counter_reset,
            ),
            rate_limited: delta(a.rate_limited, b.rate_limited, &mut counter_reset),
            conn_limit_rejected: delta(
                a.conn_limit_rejected,
                b.conn_limit_rejected,
                &mut counter_reset,
            ),
            firewall_denied: delta(a.firewall_denied, b.firewall_denied, &mut counter_reset),
            user_rate_rejected: delta(
                a.user_rate_rejected,
                b.user_rate_rejected,
                &mut counter_reset,
            ),
            cover_forwards: delta(a.cover_forwards, b.cover_forwards, &mut counter_reset),
            tx_bytes: delta(a.tx_bytes, b.tx_bytes, &mut counter_reset),
            rx_bytes: delta(a.rx_bytes, b.rx_bytes, &mut counter_reset),
            aead_drops: delta(a.aead_drops, b.aead_drops, &mut counter_reset),
            ratchets: delta(a.ratchets, b.ratchets, &mut counter_reset),
            session_idle_reaped: delta(
                a.session_idle_reaped,
                b.session_idle_reaped,
                &mut counter_reset,
            ),
            session_byte_budget_exhausted: delta(
                a.session_byte_budget_exhausted,
                b.session_byte_budget_exhausted,
                &mut counter_reset,
            ),
            now_in_flight: b.in_flight_sessions,
            now_up: b.up,
            now_ready: b.ready,
            counter_reset,
        }
    }

    /// Sum of all rejection deltas — one-glance "is anything being
    /// rejected RIGHT NOW?".
    #[must_use]
    pub fn total_rejected(&self) -> u64 {
        self.firewall_denied
            .saturating_add(self.handshake_budget_rejected)
            .saturating_add(self.rate_limited)
            .saturating_add(self.conn_limit_rejected)
            .saturating_add(self.user_rate_rejected)
    }
}

impl fmt::Display for MetricsDelta {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let live_marker = if self.now_up == 1 { "LIVE" } else { "DOWN" };
        let ready_marker = if self.now_ready == 1 {
            "READY"
        } else {
            "DRAINING"
        };
        writeln!(
            f,
            "============================================================"
        )?;
        writeln!(
            f,
            " proteus-server delta over {:.1}s — {live_marker} / {ready_marker}",
            self.interval_secs,
        )?;
        writeln!(
            f,
            "============================================================"
        )?;
        if self.counter_reset {
            writeln!(
                f,
                " ⚠  counter reset detected between scrapes — likely a process restart"
            )?;
            writeln!(
                f,
                "------------------------------------------------------------"
            )?;
        }

        let interval = if self.interval_secs <= 0.0 {
            1.0
        } else {
            self.interval_secs
        };

        macro_rules! row_rate {
            ($label:expr, $value:expr) => {{
                let rate = $value as f64 / interval;
                writeln!(f, "  {:<32} {:>9} ({:>6.2}/s)", $label, $value, rate)
            }};
        }
        macro_rules! row {
            ($label:expr, $value:expr) => {
                writeln!(f, "  {:<32} {}", $label, $value)
            };
        }

        writeln!(f, " Sessions (delta)")?;
        row!("in_flight_sessions (gauge)", self.now_in_flight)?;
        row_rate!("sessions_accepted", self.sessions_accepted)?;
        row_rate!("handshakes_succeeded", self.handshakes_succeeded)?;
        row_rate!("handshakes_failed", self.handshakes_failed)?;
        row_rate!("handshake_timeouts", self.handshake_timeouts)?;
        writeln!(f)?;

        writeln!(f, " Defense pipeline (rejections delta)")?;
        row_rate!("firewall_denied", self.firewall_denied)?;
        row_rate!("handshake_budget_rejected", self.handshake_budget_rejected)?;
        row_rate!("rate_limited", self.rate_limited)?;
        row_rate!("conn_limit_rejected", self.conn_limit_rejected)?;
        row_rate!("user_rate_rejected", self.user_rate_rejected)?;
        row_rate!("cover_forwards", self.cover_forwards)?;
        row_rate!("total_rejected", self.total_rejected())?;
        writeln!(f)?;

        writeln!(f, " Session teardown (delta)")?;
        row_rate!("session_idle_reaped", self.session_idle_reaped)?;
        row_rate!(
            "session_byte_budget_exhausted",
            self.session_byte_budget_exhausted
        )?;
        writeln!(f)?;

        writeln!(f, " Throughput (delta)")?;
        let tx_rate = self.tx_bytes as f64 / interval;
        let rx_rate = self.rx_bytes as f64 / interval;
        writeln!(
            f,
            "  {:<32} {:>9} ({}/s)",
            "tx_bytes",
            self.tx_bytes,
            human_bytes_rate(tx_rate)
        )?;
        writeln!(
            f,
            "  {:<32} {:>9} ({}/s)",
            "rx_bytes",
            self.rx_bytes,
            human_bytes_rate(rx_rate)
        )?;
        row_rate!("ratchets", self.ratchets)?;
        row_rate!("aead_drops", self.aead_drops)?;
        writeln!(
            f,
            "============================================================"
        )?;
        Ok(())
    }
}

fn human_bytes_rate(per_sec: f64) -> String {
    const KIB: f64 = 1024.0;
    const MIB: f64 = 1024.0 * KIB;
    const GIB: f64 = 1024.0 * MIB;
    if per_sec >= GIB {
        format!("{:.2} GiB", per_sec / GIB)
    } else if per_sec >= MIB {
        format!("{:.2} MiB", per_sec / MIB)
    } else if per_sec >= KIB {
        format!("{:.2} KiB", per_sec / KIB)
    } else {
        format!("{per_sec:.1} B")
    }
}

/// Driver for `admin diff` — read two saved exposition bodies from
/// disk, compute the delta, print. Both files are expected to be
/// the raw `/metrics` text; the operator captures them with e.g.
/// `proteus-server admin status --raw > /tmp/before` (we don't ship
/// `--raw` today but `curl` works fine).
pub fn run_diff(
    a_path: &Path,
    b_path: &Path,
    interval_secs: f64,
) -> Result<(), Box<dyn std::error::Error>> {
    let a_text = std::fs::read_to_string(a_path).map_err(|e| format!("read {a_path:?}: {e}"))?;
    let b_text = std::fs::read_to_string(b_path).map_err(|e| format!("read {b_path:?}: {e}"))?;
    let a = MetricsSnapshot::parse(&a_text);
    let b = MetricsSnapshot::parse(&b_text);
    let d = MetricsDelta::between(&a, &b, interval_secs);
    let _ = std::io::stdout().write_all(d.to_string().as_bytes());
    Ok(())
}

/// Driver for `admin watch` — loop forever scraping `/metrics` at
/// `interval`, printing deltas between successive scrapes. The
/// FIRST iteration prints the absolute snapshot (no delta source);
/// subsequent iterations print the delta. Ctrl-C exits cleanly.
pub fn run_watch(
    url: &str,
    token: Option<&str>,
    timeout: Duration,
    interval: Duration,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut prev: Option<(MetricsSnapshot, std::time::Instant)> = None;
    loop {
        let body = http_get(url, token, timeout)?;
        let now = std::time::Instant::now();
        let cur = MetricsSnapshot::parse(&body);
        // ANSI clear-screen + cursor-home, so `watch`-like output
        // doesn't accumulate. Skipped when stdout isn't a TTY (a
        // pipe would record the escape codes).
        if is_tty_stdout() {
            let _ = std::io::stdout().write_all(b"\x1b[2J\x1b[H");
        }
        match &prev {
            None => {
                let _ = std::io::stdout().write_all(cur.to_string().as_bytes());
            }
            Some((before, t0)) => {
                let secs = now.duration_since(*t0).as_secs_f64();
                let d = MetricsDelta::between(before, &cur, secs);
                let _ = std::io::stdout().write_all(d.to_string().as_bytes());
            }
        }
        prev = Some((cur, now));
        std::thread::sleep(interval);
    }
}

fn is_tty_stdout() -> bool {
    // Conservative check: `cargo test` captures stdout, and CI is
    // usually non-TTY. We use `IsTerminal` from std (1.70+) which is
    // already MSRV-clean.
    use std::io::IsTerminal;
    std::io::stdout().is_terminal()
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
# HELP proteus_up Server alive.
# TYPE proteus_up gauge
proteus_up 1
# HELP proteus_ready Server ready.
# TYPE proteus_ready gauge
proteus_ready 1
# HELP proteus_in_flight_sessions In-flight sessions.
# TYPE proteus_in_flight_sessions gauge
proteus_in_flight_sessions 7
proteus_sessions_accepted_total 100
proteus_handshakes_succeeded_total 95
proteus_handshakes_failed_total 5
proteus_handshake_timeouts_total 2
proteus_handshake_budget_rejected_total 3
proteus_rate_limited_total 11
proteus_conn_limit_rejected_total 13
proteus_firewall_denied_total 17
proteus_user_rate_rejected_total 19
proteus_cover_forwards_total 23
proteus_tx_bytes_total 1048576
proteus_rx_bytes_total 2097152
proteus_aead_drops_total 0
proteus_ratchets_total 31
proteus_session_idle_reaped_total 37
proteus_session_byte_budget_exhausted_total 41
proteus_some_future_counter_total 43
";

    #[test]
    fn parse_recognizes_every_known_counter() {
        let s = MetricsSnapshot::parse(SAMPLE);
        assert_eq!(s.up, 1);
        assert_eq!(s.ready, 1);
        assert_eq!(s.in_flight_sessions, 7);
        assert_eq!(s.sessions_accepted, 100);
        assert_eq!(s.handshakes_succeeded, 95);
        assert_eq!(s.handshakes_failed, 5);
        assert_eq!(s.handshake_timeouts, 2);
        assert_eq!(s.handshake_budget_rejected, 3);
        assert_eq!(s.rate_limited, 11);
        assert_eq!(s.conn_limit_rejected, 13);
        assert_eq!(s.firewall_denied, 17);
        assert_eq!(s.user_rate_rejected, 19);
        assert_eq!(s.cover_forwards, 23);
        assert_eq!(s.tx_bytes, 1_048_576);
        assert_eq!(s.rx_bytes, 2_097_152);
        assert_eq!(s.aead_drops, 0);
        assert_eq!(s.ratchets, 31);
        assert_eq!(s.session_idle_reaped, 37);
        assert_eq!(s.session_byte_budget_exhausted, 41);
    }

    #[test]
    fn parse_keeps_unknown_counters_under_other() {
        let s = MetricsSnapshot::parse(SAMPLE);
        // Forward-compat: unknown but prefixed-proteus_ counters
        // should land in `other`.
        assert_eq!(s.other.get("proteus_some_future_counter_total"), Some(&43));
    }

    #[test]
    fn parse_ignores_non_proteus_counters() {
        let body = "go_goroutines 42\nproteus_up 1\n";
        let s = MetricsSnapshot::parse(body);
        assert_eq!(s.up, 1);
        assert!(s.other.is_empty());
    }

    #[test]
    fn parse_ignores_label_bearing_series() {
        // We don't currently emit labels, but the parser must not
        // misread them as known counters.
        let body = "proteus_up{foo=\"bar\"} 99\nproteus_up 1\n";
        let s = MetricsSnapshot::parse(body);
        assert_eq!(
            s.up, 1,
            "label-bearing line must NOT override the plain line"
        );
    }

    #[test]
    fn parse_tolerates_malformed_lines() {
        let body = "proteus_up not-a-number\nproteus_ready 1\n\
                    garbage\nproteus_in_flight_sessions 5\n";
        let s = MetricsSnapshot::parse(body);
        assert_eq!(s.ready, 1);
        assert_eq!(s.in_flight_sessions, 5);
        assert_eq!(s.up, 0, "malformed value should leave default");
    }

    #[test]
    fn total_rejected_sums_correctly() {
        let s = MetricsSnapshot::parse(SAMPLE);
        // firewall(17) + budget(3) + rate(11) + conn(13) + user(19) = 63
        assert_eq!(s.total_rejected(), 63);
    }

    #[test]
    fn display_shows_live_when_up_and_ready() {
        let s = MetricsSnapshot::parse(SAMPLE);
        let out = s.to_string();
        assert!(out.contains("LIVE / READY"));
    }

    #[test]
    fn display_shows_down_when_not_up() {
        let s = MetricsSnapshot {
            ready: 1,
            ..MetricsSnapshot::default()
        };
        let out = s.to_string();
        assert!(out.contains("DOWN"));
    }

    #[test]
    fn display_shows_draining_when_not_ready() {
        let s = MetricsSnapshot {
            up: 1,
            ..MetricsSnapshot::default()
        };
        let out = s.to_string();
        assert!(out.contains("DRAINING"));
    }

    #[test]
    fn display_shows_other_section_only_when_nonempty() {
        let s = MetricsSnapshot::default();
        let out = s.to_string();
        assert!(!out.contains("Other"), "should not show empty 'Other'");

        let s = MetricsSnapshot::parse(SAMPLE);
        let out = s.to_string();
        assert!(out.contains("Other"));
    }

    #[test]
    fn display_renders_throughput_human_units() {
        let s = MetricsSnapshot::parse(SAMPLE);
        let out = s.to_string();
        assert!(out.contains("1.00 MiB"));
        assert!(out.contains("2.00 MiB"));
    }

    #[test]
    fn parse_http_url_accepts_well_formed() {
        let (h, p, path) = parse_http_url("http://127.0.0.1:9090/metrics").unwrap();
        assert_eq!(h, "127.0.0.1");
        assert_eq!(p, 9090);
        assert_eq!(path, "/metrics");
    }

    #[test]
    fn parse_http_url_rejects_https() {
        assert!(parse_http_url("https://example.com:443/metrics").is_err());
    }

    #[test]
    fn parse_http_url_rejects_missing_port() {
        assert!(parse_http_url("http://example.com/metrics").is_err());
    }

    #[test]
    fn parse_http_url_defaults_path_to_slash() {
        let (_, _, path) = parse_http_url("http://127.0.0.1:9090").unwrap();
        assert_eq!(path, "/");
    }

    #[test]
    fn read_token_file_rejects_empty() {
        let p =
            std::env::temp_dir().join(format!("proteus-admin-empty-token-{}", std::process::id()));
        std::fs::write(&p, b"\n\n  \n").unwrap();
        let r = read_token_file(&p);
        assert!(r.is_err(), "empty/whitespace-only token must fail");
        let _ = std::fs::remove_file(&p);
    }

    // ----- MetricsDelta -----

    #[test]
    fn delta_subtracts_each_counter() {
        let a = MetricsSnapshot::parse(SAMPLE);
        let mut b = a.clone();
        b.sessions_accepted += 17;
        b.firewall_denied += 3;
        b.tx_bytes += 4096;
        let d = MetricsDelta::between(&a, &b, 10.0);
        assert_eq!(d.sessions_accepted, 17);
        assert_eq!(d.firewall_denied, 3);
        assert_eq!(d.tx_bytes, 4096);
        // Other counters are zero.
        assert_eq!(d.rate_limited, 0);
        assert!(!d.counter_reset);
    }

    #[test]
    fn delta_detects_counter_reset() {
        let a = MetricsSnapshot::parse(SAMPLE);
        // Simulate a process restart: every counter drops to a small
        // fresh value.
        let b = MetricsSnapshot {
            sessions_accepted: 1,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 30.0);
        assert!(d.counter_reset, "must flag counter_reset");
        // Clamped to 0, not wrapping.
        assert_eq!(d.handshakes_succeeded, 0);
        assert_eq!(d.firewall_denied, 0);
    }

    #[test]
    fn delta_carries_current_gauges() {
        let a = MetricsSnapshot::default();
        let b = MetricsSnapshot {
            in_flight_sessions: 42,
            up: 1,
            ready: 1,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 5.0);
        assert_eq!(d.now_in_flight, 42);
        assert_eq!(d.now_up, 1);
        assert_eq!(d.now_ready, 1);
    }

    #[test]
    fn delta_total_rejected_sums_correctly() {
        let a = MetricsSnapshot::default();
        let b = MetricsSnapshot {
            firewall_denied: 3,
            handshake_budget_rejected: 5,
            rate_limited: 7,
            conn_limit_rejected: 11,
            user_rate_rejected: 13,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 1.0);
        assert_eq!(d.total_rejected(), 3 + 5 + 7 + 11 + 13);
    }

    #[test]
    fn delta_display_renders_rates() {
        // 60 sessions accepted over 30s = 2.0/s.
        let a = MetricsSnapshot::default();
        let b = MetricsSnapshot {
            sessions_accepted: 60,
            up: 1,
            ready: 1,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 30.0);
        let out = d.to_string();
        assert!(out.contains("delta over 30.0s"));
        assert!(out.contains("LIVE / READY"));
        // Format is `sessions_accepted   60 (  2.00/s)`.
        assert!(out.contains("2.00/s"), "expected 2.00/s rate: {out}");
    }

    #[test]
    fn delta_display_renders_reset_banner() {
        let a = MetricsSnapshot::parse(SAMPLE);
        let b = MetricsSnapshot::default(); // every counter wiped
        let d = MetricsDelta::between(&a, &b, 30.0);
        let out = d.to_string();
        assert!(
            out.contains("counter reset"),
            "expected reset banner: {out}"
        );
    }

    #[test]
    fn delta_handles_zero_interval_without_dividing_by_zero() {
        let a = MetricsSnapshot::default();
        let b = MetricsSnapshot {
            sessions_accepted: 10,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 0.0);
        // Display must not panic and must not emit `inf`.
        let out = d.to_string();
        assert!(!out.contains("inf"), "got: {out}");
    }

    #[test]
    fn delta_throughput_renders_in_human_units() {
        let a = MetricsSnapshot::default();
        // 10 MiB over 10s → 1.0 MiB/s.
        let b = MetricsSnapshot {
            tx_bytes: 10 * 1024 * 1024,
            up: 1,
            ready: 1,
            ..MetricsSnapshot::default()
        };
        let d = MetricsDelta::between(&a, &b, 10.0);
        let out = d.to_string();
        assert!(out.contains("1.00 MiB/s"), "expected 1 MiB/s: {out}");
    }

    #[test]
    fn read_token_file_strips_trailing_whitespace() {
        let p = std::env::temp_dir().join(format!("proteus-admin-ok-token-{}", std::process::id()));
        std::fs::write(&p, b"abcdef0123\n").unwrap();
        let t = read_token_file(&p).unwrap();
        assert_eq!(t, "abcdef0123");
        let _ = std::fs::remove_file(&p);
    }
}
