//! `proteus-server keygen` subcommand.
//!
//! Generates a fresh long-term server keypair set:
//! - ML-KEM-768 (FIPS-203) PQ encapsulation / decapsulation keypair.
//! - X25519 (RFC 7748) classical ECDH keypair.
//! - PQ-fingerprint = SHA-256(mlkem_pk), used as the HKDF salt for the
//!   handshake auth-tag derivation (spec §4.1.3) and as the client-id
//!   AEAD key derivation salt (spec §5.7).
//!
//! Files are written with mode 0600 on Unix.

use std::fs;
use std::path::Path;

use base64::Engine;
use ml_kem::{EncodedSizeUser, KemCore, MlKem768};
use proteus_crypto::key_schedule;
use rand_core::OsRng;
use x25519_dalek::{PublicKey as XPublicKey, StaticSecret};

pub fn run(out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(out_dir)?;
    let mut rng = OsRng;

    // ---- ML-KEM-768 ----
    let (mlkem_sk, mlkem_pk) = MlKem768::generate(&mut rng);
    let mlkem_pk_bytes = mlkem_pk.as_bytes().to_vec();
    let mlkem_sk_bytes = mlkem_sk.as_bytes().to_vec();
    write_b64(&out_dir.join("server_lt.mlkem768.pk"), &mlkem_pk_bytes)?;
    write_b64(&out_dir.join("server_lt.mlkem768.sk"), &mlkem_sk_bytes)?;
    let fingerprint = key_schedule::sha256(&mlkem_pk_bytes);
    write_b64(&out_dir.join("server_lt.pq.fingerprint"), &fingerprint)?;

    // ---- X25519 ----
    //
    // Use `StaticSecret` (not `ReusableSecret`) because we need to
    // serialize the raw bytes to disk. `pk` and `sk` MUST be derived
    // from the same draw to be a valid keypair.
    let x_sk = StaticSecret::random_from_rng(rng);
    let x_pub = XPublicKey::from(&x_sk);
    write_b64(&out_dir.join("server_lt.x25519.pk"), x_pub.as_bytes())?;
    write_b64(&out_dir.join("server_lt.x25519.sk"), &x_sk.to_bytes())?;

    let readme = "Generated by proteus-server keygen.\n\
         Files:\n\
           server_lt.mlkem768.pk     FIPS-203 ML-KEM-768 encapsulation key\n\
           server_lt.mlkem768.sk     FIPS-203 ML-KEM-768 decapsulation key (KEEP SECRET)\n\
           server_lt.pq.fingerprint  SHA-256(mlkem768.pk), publish in HTTPS RR\n\
           server_lt.x25519.pk       RFC 7748 X25519 long-term public key\n\
           server_lt.x25519.sk       RFC 7748 X25519 long-term secret key (KEEP SECRET)\n\
         \n\
         Distribute *.pk + *.fingerprint via your subscription channel.\n\
         Keep *.sk on the server, chmod 0600.\n";
    fs::write(out_dir.join("README"), readme)?;

    println!("✓ keypair written to {}", out_dir.display());
    Ok(())
}

fn write_b64(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let b64 = base64::engine::general_purpose::STANDARD.encode(bytes);
    fs::write(path, format!("{b64}\n"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perm = fs::metadata(path)?.permissions();
        perm.set_mode(0o600);
        fs::set_permissions(path, perm)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use x25519_dalek::StaticSecret;

    #[test]
    fn x25519_keypair_round_trips() {
        // Verify that loading the sk bytes back produces the same pk —
        // catches the keygen-mismatch bug class.
        let tmp = std::env::temp_dir().join("proteus_keygen_test");
        let _ = std::fs::remove_dir_all(&tmp);
        run(&tmp).unwrap();

        let pk_b64 = std::fs::read_to_string(tmp.join("server_lt.x25519.pk")).unwrap();
        let sk_b64 = std::fs::read_to_string(tmp.join("server_lt.x25519.sk")).unwrap();
        let pk_bytes = base64::engine::general_purpose::STANDARD
            .decode(pk_b64.trim())
            .unwrap();
        let sk_bytes = base64::engine::general_purpose::STANDARD
            .decode(sk_b64.trim())
            .unwrap();
        let sk_arr: [u8; 32] = sk_bytes.as_slice().try_into().unwrap();
        let sk = StaticSecret::from(sk_arr);
        let derived_pk = XPublicKey::from(&sk);
        assert_eq!(
            derived_pk.as_bytes()[..],
            pk_bytes[..],
            "x25519 sk and pk on disk MUST form a valid keypair"
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn fingerprint_matches_pk_hash() {
        let tmp = std::env::temp_dir().join("proteus_keygen_fp_test");
        let _ = std::fs::remove_dir_all(&tmp);
        run(&tmp).unwrap();

        let pk_b64 = std::fs::read_to_string(tmp.join("server_lt.mlkem768.pk")).unwrap();
        let fp_b64 = std::fs::read_to_string(tmp.join("server_lt.pq.fingerprint")).unwrap();
        let pk = base64::engine::general_purpose::STANDARD
            .decode(pk_b64.trim())
            .unwrap();
        let fp = base64::engine::general_purpose::STANDARD
            .decode(fp_b64.trim())
            .unwrap();
        let expected = key_schedule::sha256(&pk);
        assert_eq!(&fp[..], &expected[..]);
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
