//! `proteus-server keygen` subcommand.
//!
//! Generates a fresh long-term server keypair set:
//! - ML-KEM-768 (FIPS-203) PQ encapsulation / decapsulation keypair.
//! - X25519 (RFC 7748) classical ECDH keypair.
//! - PQ-fingerprint = SHA-256(mlkem_pk), used as the HKDF salt for the
//!   handshake auth-tag derivation (spec §4.1.3) and as the client-id
//!   AEAD key derivation salt (spec §5.7).
//!
//! Files are written with mode 0600 on Unix.

use std::fs;
use std::path::Path;

use base64::Engine;
use ml_kem::{EncodedSizeUser, KemCore, MlKem768};
use proteus_crypto::key_schedule;
use rand_core::OsRng;
use x25519_dalek::{PublicKey as XPublicKey, StaticSecret};

#[allow(dead_code)] // stable lib surface; binary calls run_with_force
pub fn run(out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    run_with_force(out_dir, false)
}

/// Iter-130: same as [`run`] but with explicit `force` flag.
/// `force=true` mirrors the pre-iter-130 behavior (overwrite any
/// existing key file). `force=false` (the default for the CLI)
/// refuses if ANY of the 6 bundle files exists at the target path
/// — preventing the operator from accidentally re-running keygen
/// over a production key bundle. The keys MUST be replaced as a
/// set (mlkem_sk + mlkem_pk + fingerprint + x25519_sk + x25519_pk
/// are cryptographically bound together) so even a partial
/// overwrite of one file would corrupt the bundle.
pub fn run_with_force(
    out_dir: &Path,
    force: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    // Iter-130: pre-check all 6 target paths. If ANY exists and
    // !force, refuse before generating any new keys.
    let targets = [
        out_dir.join("server_lt.mlkem768.pk"),
        out_dir.join("server_lt.mlkem768.sk"),
        out_dir.join("server_lt.pq.fingerprint"),
        out_dir.join("server_lt.x25519.pk"),
        out_dir.join("server_lt.x25519.sk"),
        out_dir.join("README"),
    ];
    if !force {
        for p in &targets {
            if p.exists() {
                return Err(format!(
                    "refusing to overwrite existing key file {}. The current \
                     server identity bundle is in active use — every client's \
                     `server.pq.fingerprint` pin would mismatch the new \
                     mlkem768.pk and reject the handshake with \
                     'fingerprint mismatch' on the very next connect. If you \
                     ARE deliberately rotating: 1) pre-distribute the new \
                     fingerprint to every client (out-of-band), 2) re-run \
                     with `--force` to overwrite, 3) restart the server. If \
                     you're not rotating, pick a different `--out` directory \
                     (the bundle keys must be co-located so don't try to \
                     hand-merge into an existing dir).",
                    p.display()
                )
                .into());
            }
        }
    }
    fs::create_dir_all(out_dir)?;
    let mut rng = OsRng;

    // ---- ML-KEM-768 ----
    let (mlkem_sk, mlkem_pk) = MlKem768::generate(&mut rng);
    let mlkem_pk_bytes = mlkem_pk.as_bytes().to_vec();
    let mlkem_sk_bytes = mlkem_sk.as_bytes().to_vec();
    write_b64(&out_dir.join("server_lt.mlkem768.pk"), &mlkem_pk_bytes)?;
    write_b64(&out_dir.join("server_lt.mlkem768.sk"), &mlkem_sk_bytes)?;
    let fingerprint = key_schedule::sha256(&mlkem_pk_bytes);
    write_b64(&out_dir.join("server_lt.pq.fingerprint"), &fingerprint)?;

    // ---- X25519 ----
    //
    // Use `StaticSecret` (not `ReusableSecret`) because we need to
    // serialize the raw bytes to disk. `pk` and `sk` MUST be derived
    // from the same draw to be a valid keypair.
    let x_sk = StaticSecret::random_from_rng(rng);
    let x_pub = XPublicKey::from(&x_sk);
    write_b64(&out_dir.join("server_lt.x25519.pk"), x_pub.as_bytes())?;
    write_b64(&out_dir.join("server_lt.x25519.sk"), &x_sk.to_bytes())?;

    let readme = "Generated by proteus-server keygen.\n\
         Files:\n\
           server_lt.mlkem768.pk     FIPS-203 ML-KEM-768 encapsulation key\n\
           server_lt.mlkem768.sk     FIPS-203 ML-KEM-768 decapsulation key (KEEP SECRET)\n\
           server_lt.pq.fingerprint  SHA-256(mlkem768.pk), publish in HTTPS RR\n\
           server_lt.x25519.pk       RFC 7748 X25519 long-term public key\n\
           server_lt.x25519.sk       RFC 7748 X25519 long-term secret key (KEEP SECRET)\n\
         \n\
         Distribute *.pk + *.fingerprint via your subscription channel.\n\
         Keep *.sk on the server, chmod 0600.\n";
    fs::write(out_dir.join("README"), readme)?;

    println!("✓ keypair written to {}", out_dir.display());
    Ok(())
}

fn write_b64(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let b64 = base64::engine::general_purpose::STANDARD.encode(bytes);
    fs::write(path, format!("{b64}\n"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perm = fs::metadata(path)?.permissions();
        perm.set_mode(0o600);
        fs::set_permissions(path, perm)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use x25519_dalek::StaticSecret;

    #[test]
    fn x25519_keypair_round_trips() {
        // Verify that loading the sk bytes back produces the same pk —
        // catches the keygen-mismatch bug class.
        let tmp = std::env::temp_dir().join("proteus_keygen_test");
        let _ = std::fs::remove_dir_all(&tmp);
        run(&tmp).unwrap();

        let pk_b64 = std::fs::read_to_string(tmp.join("server_lt.x25519.pk")).unwrap();
        let sk_b64 = std::fs::read_to_string(tmp.join("server_lt.x25519.sk")).unwrap();
        let pk_bytes = base64::engine::general_purpose::STANDARD
            .decode(pk_b64.trim())
            .unwrap();
        let sk_bytes = base64::engine::general_purpose::STANDARD
            .decode(sk_b64.trim())
            .unwrap();
        let sk_arr: [u8; 32] = sk_bytes.as_slice().try_into().unwrap();
        let sk = StaticSecret::from(sk_arr);
        let derived_pk = XPublicKey::from(&sk);
        assert_eq!(
            derived_pk.as_bytes()[..],
            pk_bytes[..],
            "x25519 sk and pk on disk MUST form a valid keypair"
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn fingerprint_matches_pk_hash() {
        let tmp = std::env::temp_dir().join("proteus_keygen_fp_test");
        let _ = std::fs::remove_dir_all(&tmp);
        run(&tmp).unwrap();

        let pk_b64 = std::fs::read_to_string(tmp.join("server_lt.mlkem768.pk")).unwrap();
        let fp_b64 = std::fs::read_to_string(tmp.join("server_lt.pq.fingerprint")).unwrap();
        let pk = base64::engine::general_purpose::STANDARD
            .decode(pk_b64.trim())
            .unwrap();
        let fp = base64::engine::general_purpose::STANDARD
            .decode(fp_b64.trim())
            .unwrap();
        let expected = key_schedule::sha256(&pk);
        assert_eq!(&fp[..], &expected[..]);
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
