//! `proteus-server knock-keygen` subcommand.
//!
//! Mints a fresh 32-byte server-knock PSK and writes it to the
//! operator's chosen path with mode 0600. The same key must be
//! distributed (out-of-band, via the existing subscription
//! channel) to every client that should be allowed to talk to
//! this server. Probers without the key see only the cover-site
//! response — see [`proteus_handshake::knock`] for the
//! cryptographic property.
//!
//! ## Why a separate command from `keygen`
//!
//! `proteus-server keygen` mints the long-term identity bundle
//! (ML-KEM, X25519, fingerprint). Those keys MUST stay paired —
//! rotating one without the others breaks authentication. The
//! knock PSK is **operationally independent**: operators may want
//! to rotate it more frequently than the identity bundle (e.g.
//! after a client device is lost), and they may want to rotate
//! it less frequently if their distribution channel is expensive.
//! Splitting the commands lets each lifecycle move on its own
//! cadence.
//!
//! ## File format
//!
//! Single line, base64-standard-encoded, no padding stripped
//! (matches `keygen`'s `*.pk` / `*.sk` format). 32 bytes of
//! `OsRng`-sourced random:
//!
//! ```text
//!   2cYBzN8...P9w=
//! ```
//!
//! Mode 0600 on Unix. Operators distributing via `scp` /
//! `age` / shared-secret channel preserve the leading-comment
//! `Generated by proteus-server knock-keygen` so future audit
//! tooling can identify provenance.
//!
//! ## Wire/distribution channel
//!
//! Same out-of-band channel the operator already uses for the
//! `server_lt.*.pk` files. Specifically NOT through the proxy
//! itself (chicken-and-egg) and NOT through email/Telegram in
//! plain text (one leaked PSK = every probe can pass). Operator
//! options:
//!   * `scp` from a trusted bastion
//!   * Encrypted via `age -r <recipient>`
//!   * Out-of-band 256-bit hex string copied through Signal /
//!     iMessage end-to-end (the bytes are 32 random bytes —
//!     hex-encoded is 64 chars, fits in one message).

use std::fs;
use std::path::Path;

use base64::Engine;
use proteus_handshake::knock::KNOCK_PSK_LEN;
use rand_core::{OsRng, RngCore};
use zeroize::{Zeroize as _, Zeroizing};

/// Mint a fresh PSK and write it to `out_path`. Returns the
/// PSK bytes so the caller (mostly tests) can verify.
///
/// On Unix the file is chmod'd to 0600 immediately after write
/// — the window between create and chmod is the standard
/// keygen race window (which `fs::write` opens with default
/// 0644 then we tighten). Operators concerned about this window
/// can run from inside `umask 0177` which makes the initial
/// create 0600.
///
/// **Anti-clobber** (iter-130): refuses to overwrite an existing
/// file at `out_path` by default. Pre-iter-130 this function
/// silently clobbered any file at the target path with the new
/// PSK + 0600 mode — a fat-fingered `--out /etc/passwd` would
/// have been a real disaster. Callers wanting to deliberately
/// rotate must use [`run_with_force`].
// `run` is the no-force convenience wrapper kept as a stable
// lib surface for tests + future callers. The `proteus-server`
// binary calls `run_with_force` directly so it can wire the
// `--force` CLI flag.
#[allow(dead_code)]
pub fn run(out_path: &Path) -> Result<[u8; KNOCK_PSK_LEN], Box<dyn std::error::Error>> {
    run_with_force(out_path, false)
}

/// Iter-130: same as [`run`] but with explicit `force` flag.
/// `force=true` mirrors the pre-iter-130 behavior (silent
/// overwrite) for the deliberate-rotation case driven by the
/// CLI `--force` flag.
pub fn run_with_force(
    out_path: &Path,
    force: bool,
) -> Result<[u8; KNOCK_PSK_LEN], Box<dyn std::error::Error>> {
    if !force && out_path.exists() {
        return Err(format!(
            "refusing to overwrite existing file {}. The previous knock PSK \
             is still in use by every client; clobbering it would \
             immediately break every active session AND every future \
             connect (clients would send knocks signed with the old PSK \
             which the server would reject). If you ARE deliberately \
             rotating: 1) pre-stage the new PSK to every client \
             out-of-band, 2) re-run with `--force` to overwrite, \
             3) cycle the server. If you're not rotating, pick a \
             different `--out` path or remove the file first.",
            out_path.display()
        )
        .into());
    }
    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }
    // Iter-167: wrap the PSK + its base64 string + the file body
    // in `Zeroizing` so all three secret-bearing buffers are
    // scrubbed on drop. Pre-iter-167 the raw `[u8; 32]` PSK and
    // the base64 string (which is directly substitutable for the
    // PSK via b64-decode) lingered in the function's stack frame
    // through the file-write syscall and after the function
    // returned, until later activity overwrites them. A
    // coredump during the brief write window can recover the
    // PSK — and the knock PSK is the entire authentication
    // boundary on Path A (every client uses it; rotation requires
    // re-distributing to every client out-of-band).
    let mut key = Zeroizing::new([0u8; KNOCK_PSK_LEN]);
    OsRng.fill_bytes(&mut *key);
    let mut b64 = base64::engine::general_purpose::STANDARD.encode(*key);
    // Two-line file: leading "Generated by ..." comment, then
    // the b64 key. Comment is operator-visible audit provenance;
    // the loader (in config.rs follow-up) strips lines starting
    // with `#`.
    let mut body = format!(
        "# Generated by proteus-server knock-keygen — server-side knock PSK\n\
         # 32 bytes (256 bits) of OsRng. KEEP SECRET. chmod 0600.\n\
         {b64}\n"
    );
    // Iter-152: same atomic-mode-0600 + fsync pattern as
    // `keygen::write_b64`. The knock PSK is a 32-byte server
    // secret in the same compromise category as the ML-KEM /
    // X25519 SK files; a write-then-chmod race window is a real
    // exfil vector on a shared host.
    let write_result = (|| -> Result<(), Box<dyn std::error::Error>> {
        #[cfg(unix)]
        {
            use std::io::Write;
            use std::os::unix::fs::OpenOptionsExt;
            let mut f = fs::OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(0o600)
                .open(out_path)?;
            f.write_all(body.as_bytes())?;
            f.sync_all()?;
        }
        #[cfg(not(unix))]
        {
            fs::write(out_path, body.as_bytes())?;
        }
        if let Some(parent) = out_path.parent() {
            if !parent.as_os_str().is_empty() {
                if let Ok(parent_f) = fs::File::open(parent) {
                    let _ = parent_f.sync_all();
                }
            }
        }
        Ok(())
    })();
    // Snapshot the unwrapped PSK BEFORE we drop the Zeroizing
    // wrappers so the caller (mostly tests) gets the original
    // bytes. The wrapped versions still scrub on function exit.
    let out_key = *key;
    // Scrub the intermediate b64 + body buffers regardless of
    // write outcome.
    b64.zeroize();
    body.zeroize();
    write_result?;
    println!(
        "✓ knock PSK ({KNOCK_PSK_LEN} bytes) written to {}",
        out_path.display()
    );
    println!(
        "  • Distribute to clients via the SAME out-of-band channel \
         you use for server_lt.*.pk files (NOT through the proxy itself \
         and NOT through email in plaintext)."
    );
    println!("  • Mode 0600 set on Unix.");
    Ok(out_key)
}

/// Parse a knock PSK file written by [`run`]: skips lines starting
/// with `#`, expects one base64 line, decodes to exactly 32 bytes.
/// Used by the config loader (follow-up) when the operator sets
/// `server_knock_psk_file:` in their YAML.
pub fn load(path: &Path) -> Result<[u8; KNOCK_PSK_LEN], LoadError> {
    let body = fs::read_to_string(path).map_err(|e| LoadError::Io(path.to_path_buf(), e))?;
    let mut data_line: Option<&str> = None;
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if data_line.is_some() {
            return Err(LoadError::MultipleDataLines(path.to_path_buf()));
        }
        data_line = Some(trimmed);
    }
    let line = data_line.ok_or_else(|| LoadError::Empty(path.to_path_buf()))?;
    let raw = base64::engine::general_purpose::STANDARD
        .decode(line)
        .map_err(|e| LoadError::Base64(path.to_path_buf(), e.to_string()))?;
    if raw.len() != KNOCK_PSK_LEN {
        return Err(LoadError::WrongLength {
            path: path.to_path_buf(),
            got: raw.len(),
            want: KNOCK_PSK_LEN,
        });
    }
    let mut out = [0u8; KNOCK_PSK_LEN];
    out.copy_from_slice(&raw);
    Ok(out)
}

/// Loader-side errors. Distinct from anything else in the
/// codebase so the YAML-load path can surface "knock_psk_file
/// invalid" with an actionable message.
#[derive(thiserror::Error, Debug)]
pub enum LoadError {
    /// File could not be opened / read.
    #[error("io {0:?}: {1}")]
    Io(std::path::PathBuf, std::io::Error),
    /// File contained no non-comment lines.
    #[error("{0:?}: empty (no non-comment data line)")]
    Empty(std::path::PathBuf),
    /// File contained more than one non-comment data line.
    /// Operators editing the file by hand may have appended a
    /// second key; reject so the loader doesn't silently use
    /// the first or last.
    #[error("{0:?}: multiple non-comment data lines — should be exactly one b64 line")]
    MultipleDataLines(std::path::PathBuf),
    /// Base64 decode failed.
    #[error("{0:?}: base64 decode failed: {1}")]
    Base64(std::path::PathBuf, String),
    /// Decoded byte length didn't match the protocol-required 32.
    #[error("{path:?}: decoded {got} bytes, expected {want}")]
    WrongLength {
        /// The path that failed.
        path: std::path::PathBuf,
        /// What we got.
        got: usize,
        /// What the protocol requires.
        want: usize,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use proteus_handshake::knock::{compute_knock, verify_knock, KnockPsk, KNOCK_PSK_LEN};

    fn tmp_path(suffix: &str) -> std::path::PathBuf {
        let base = std::env::var("CARGO_TARGET_TMPDIR").unwrap_or_else(|_| "/tmp".to_string());
        let p = std::path::PathBuf::from(format!(
            "{base}/proteus-knock-keygen-{suffix}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        let _ = std::fs::remove_file(&p);
        p
    }

    #[test]
    fn run_writes_32_bytes_to_target_path() {
        let p = tmp_path("run-32b");
        let key = run(&p).unwrap();
        assert_eq!(key.len(), KNOCK_PSK_LEN);
        assert!(p.exists());
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn round_trip_run_then_load_recovers_same_key() {
        let p = tmp_path("round-trip");
        let mint = run(&p).unwrap();
        let loaded = load(&p).expect("load must succeed for a fresh file");
        assert_eq!(mint, loaded);
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn loaded_key_round_trips_through_knock_compute_verify() {
        // Sanity: the file we write IS usable as a real
        // KnockPsk that round-trips through the verify path.
        // Catches a "file format diverged from protocol" bug
        // class — drift between keygen output + knock-primitive
        // input.
        let p = tmp_path("compute-verify");
        run(&p).unwrap();
        let loaded = load(&p).unwrap();
        let psk = KnockPsk::from_bytes(loaded);
        let client_random = [0xCC; 32];
        let now = 1_715_900_000u64;
        let tok = compute_knock(&psk, &client_random, now);
        verify_knock(&psk, &client_random, &tok, now).expect("round-trip must verify");
        let _ = std::fs::remove_file(&p);
    }

    #[cfg(unix)]
    #[test]
    fn run_sets_file_mode_0600_on_unix() {
        use std::os::unix::fs::PermissionsExt;
        let p = tmp_path("mode-0600");
        run(&p).unwrap();
        let mode = std::fs::metadata(&p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "knock PSK file must be 0600; got {mode:o}");
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_empty_file() {
        let p = tmp_path("empty");
        std::fs::write(&p, "# comment only\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, LoadError::Empty(_)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_multiple_data_lines() {
        let p = tmp_path("multi");
        std::fs::write(&p, "# header\nFIRSTKEY==\nSECONDKEY==\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, LoadError::MultipleDataLines(_)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_bad_base64() {
        let p = tmp_path("bad-b64");
        std::fs::write(&p, "# header\n!!! not base64 !!!\n").unwrap();
        let e = load(&p).unwrap_err();
        assert!(matches!(e, LoadError::Base64(_, _)));
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn load_rejects_wrong_length() {
        // Valid base64 but only 16 bytes decoded — should fail
        // with WrongLength, not silently truncate or panic.
        let p = tmp_path("short");
        let short = base64::engine::general_purpose::STANDARD.encode([0xAB; 16]);
        std::fs::write(&p, format!("# short key\n{short}\n")).unwrap();
        let e = load(&p).unwrap_err();
        assert!(
            matches!(
                e,
                LoadError::WrongLength { got, want, .. }
                    if got == 16 && want == KNOCK_PSK_LEN
            ),
            "expected WrongLength{{got=16,want=32}}, got {e:?}"
        );
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn two_runs_produce_distinct_keys() {
        // Sanity that we use OsRng correctly + don't accidentally
        // ship a constant-key bug.
        let p1 = tmp_path("distinct-a");
        let p2 = tmp_path("distinct-b");
        let k1 = run(&p1).unwrap();
        let k2 = run(&p2).unwrap();
        assert_ne!(k1, k2, "two fresh keygen runs MUST produce distinct keys");
        let _ = std::fs::remove_file(&p1);
        let _ = std::fs::remove_file(&p2);
    }

    #[test]
    fn load_handles_missing_file() {
        let p = tmp_path("missing");
        let _ = std::fs::remove_file(&p);
        let e = load(&p).unwrap_err();
        assert!(matches!(e, LoadError::Io(_, _)));
    }
}
