//! Cross-binary invariant: server's `knock-keygen` output ↔
//! client's `knock_psk::load` consumer round-trip.
//!
//! This is the contract that holds Path A together: the server
//! mints a PSK file via `proteus-server knock-keygen`, the
//! operator distributes the bytes via scp/age, the client
//! loads the file via `proteus_client::knock_psk::load` AND
//! runs it through `proteus_handshake::knock::compute_knock`,
//! AND the server (with the same PSK loaded via its own
//! `proteus_server::knock_keygen::load`) verifies the token.
//!
//! Each crate has its own `loaded_key_round_trips_through_knock_compute_verify`
//! test that pins the local file-format ↔ protocol contract.
//! THIS test pins the CROSS-CRATE invariant: that the SAME
//! file produced by the server's writer can be loaded by the
//! client's loader and yields a key that successfully
//! round-trips end-to-end.
//!
//! Drift signal: if the server's writer or the client's loader
//! ever change shape without coordination, this test fails at
//! CI time — before deploy.

use std::path::PathBuf;

use proteus_client::knock_psk;
use proteus_handshake::knock::{compute_knock, verify_knock, KnockPsk};

fn tmp_path(suffix: &str) -> PathBuf {
    let base = std::env::var("CARGO_TARGET_TMPDIR").unwrap_or_else(|_| "/tmp".to_string());
    let p = PathBuf::from(format!(
        "{base}/proteus-knock-cross-{suffix}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    let _ = std::fs::remove_file(&p);
    p
}

/// Synthesize the EXACT byte sequence that
/// `proteus-server knock-keygen` writes — same comment header,
/// same b64 line. The client's loader MUST recover the original
/// bytes.
///
/// We inline-construct rather than `cargo run -p proteus-server
/// -- knock-keygen` because (a) test runtime, (b) we don't need
/// to test the writer's CLI path (proteus-server has its own
/// tests for that). This test pins the WIRE FORMAT specifically.
fn write_in_server_format(path: &std::path::Path, raw: &[u8; 32]) {
    use base64::Engine;
    let b64 = base64::engine::general_purpose::STANDARD.encode(raw);
    let body = format!(
        "# Generated by proteus-server knock-keygen — server-side knock PSK\n\
         # 32 bytes (256 bits) of OsRng. KEEP SECRET. chmod 0600.\n\
         {b64}\n"
    );
    std::fs::write(path, body).unwrap();
}

#[test]
fn server_format_file_loads_into_client_loader_byte_for_byte() {
    let p = tmp_path("byte-for-byte");
    let original = {
        let mut a = [0u8; 32];
        for (i, b) in a.iter_mut().enumerate() {
            *b = i as u8;
        }
        a
    };
    write_in_server_format(&p, &original);

    let loaded = knock_psk::load(&p).expect("client loader must accept server format");
    assert_eq!(*loaded, original);
    let _ = std::fs::remove_file(&p);
}

#[test]
fn loaded_psk_drives_compute_and_verify_end_to_end() {
    // Full end-to-end: write file (server side), load file
    // (client side), client computes knock token, server-side
    // (same PSK) verifies it. Failure here = the file format
    // and the cryptographic primitive have drifted.
    let p = tmp_path("e2e-compute-verify");
    let raw = [0xA5; 32];
    write_in_server_format(&p, &raw);

    let loaded = knock_psk::load(&p).unwrap();
    let psk = KnockPsk::from_bytes(*loaded);
    let client_random = [0x42; 32];
    let now = 1_720_000_000u64;
    let tok = compute_knock(&psk, &client_random, now);
    verify_knock(&psk, &client_random, &tok, now)
        .expect("server-side verify of client-minted token must pass");

    let _ = std::fs::remove_file(&p);
}

#[test]
fn two_different_psks_yield_distinct_tokens_via_client_loader() {
    // The PSK is the SECRET. Two operators with two different
    // server PSKs (e.g. server A vs server B) MUST produce
    // distinguishable knock tokens for the same client_random
    // — otherwise a token from one deployment could be replayed
    // against another.
    let p_a = tmp_path("distinct-a");
    let p_b = tmp_path("distinct-b");
    write_in_server_format(&p_a, &[0x11; 32]);
    write_in_server_format(&p_b, &[0x22; 32]);

    let psk_a = KnockPsk::from_bytes(*knock_psk::load(&p_a).unwrap());
    let psk_b = KnockPsk::from_bytes(*knock_psk::load(&p_b).unwrap());
    let client_random = [0xAA; 32];
    let now = 1_720_000_000u64;
    let tok_a = compute_knock(&psk_a, &client_random, now);
    let tok_b = compute_knock(&psk_b, &client_random, now);

    // Same timestamp prefix (4 bytes) BUT different tag suffix (12 bytes).
    assert_eq!(&tok_a[..4], &tok_b[..4]);
    assert_ne!(&tok_a[4..], &tok_b[4..]);

    // And cross-verification MUST fail.
    verify_knock(&psk_a, &client_random, &tok_b, now)
        .expect_err("token from PSK B must NOT verify against PSK A");
    verify_knock(&psk_b, &client_random, &tok_a, now)
        .expect_err("token from PSK A must NOT verify against PSK B");

    let _ = std::fs::remove_file(&p_a);
    let _ = std::fs::remove_file(&p_b);
}

#[test]
fn client_loader_rejects_truncated_distribution_file() {
    // Operator scp'd a corrupt file (e.g. truncated during
    // copy). The client's loader MUST reject — silently
    // accepting a shorter PSK would weaken security.
    let p = tmp_path("truncated");
    let raw = [0xCC; 16]; // half-length
    use base64::Engine;
    let b64 = base64::engine::general_purpose::STANDARD.encode(raw);
    std::fs::write(
        &p,
        format!(
            "# Generated by proteus-server knock-keygen\n\
             {b64}\n"
        ),
    )
    .unwrap();
    let e = knock_psk::load(&p).unwrap_err();
    assert!(
        matches!(
            e,
            knock_psk::KnockPskLoadError::WrongLength { got, want, .. }
                if got == 16 && want == 32
        ),
        "truncated PSK must surface WrongLength, got {e:?}"
    );
    let _ = std::fs::remove_file(&p);
}
